# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19466a9f94049c1fc52e2156e3d0436ca060f7bab956bb503ef4f9303867cebb5da0e2b314a87031ac600de7081344553ef6db2358cc408258c18060efe715b9

test:
  secret_key_base: 71dcc26e270e3124e71e00bf28d6d3ac054caa2ebe23d9d40d437c7c54e57161cb5db369685c6ff56408feef4d7d11ec6dd71ef7787b86fb7f8f1cbe7334106e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
